#!/usr/bin/perl
use strict;
use warnings;

use Getopt::Long qw(GetOptions);
use SQL::Beautify;


my %opt;

GetOptions(\%opt,
	'spaces=i',
	'help' => sub { usage(); },
);
usage() unless @ARGV || ! -t 0;

my $orig_sql = eval {
	local $/ = undef;
	<>;
};

my $sql = SQL::Beautify->new(%opt);
$sql->query($orig_sql);
my $nice_sql = $sql->beautify;
print $nice_sql;

sub usage {
	print <<"END_USAGE";
v$SQL::Beautify::VERSION
Usage: $0 [options] FILEs

      --spaces 4      - number of indentation spaces (defaults to 4)
      
      --help          - this help
END_USAGE
	exit;
}

